### ISSUE TITLE
Monitoring CPU and memory usage

### ISSUE THREAD

**Issue by hoyu310** [aws-samples/amazon-omics-tutorials#57]
For Nextflow workflows, to be able to conveniently find out the actual CPU and memory usage of each run process, is it (optionally) possible to have a copy of the [-with-report, -with-trace, and -with-timeline outputs](https://www.nextflow.io/docs/latest/tracing.html#execution-report) in the S3 output destination?

In your current documentation about [monitoring AWS HealthOmics](https://docs.aws.amazon.com/omics/latest/dev/monitoring-overview.html), I tried following the steps to view metrics in the CloudWatch console, but this for me only provided the Metric "CallCount" of Omics CreateWorkflow, StartRun, and DeleteWorkflow, and I couldn't find things related to CPU and memory usage.

**Comment by wleepang** [comment]
Generating Nextflow specific `report`, `trace`, and `timeline` outputs is not supported in HealthOmics. Enabling them in `nextflow.config` will be ignored.

However, HealthOmics provides alternatives that are available across all workflow languages supported. All of the information you would typically find in Nextflow `trace` and `timeline` outputs are available in a run's "manifest" log. These are generated when a run completes and are a CloudWatch log-group+log-stream of the form:

```
log-group: /aws/omics/WorkflowLog
log-stream: manifest/run/{{run-id}}/{{run-uuid}}
```

This log-stream will have a first event that captures:
- how the run was invoked
  - what workflow digest was used,
  - what parameters were specified,
  - what IAM role was used,
  - other API parameters specified.
- what resources were used
  - etags for S3 objects
  - sha256 digests for container images

All remaining events will have details for all the tasks executed. This includes
- what omics instance type was used
- what compute resources (e.g. CPU, RAM, GPU) were requested
- what compute resources were actually used (e.g. avg and max for CPU and RAM) 

Information in the "manifest" log is used by tooling, like the [run-analyzer](https://github.com/awslabs/amazon-omics-tools?tab=readme-ov-file#using-the-omics-run-analyzer-tool), to create cost and performance analysis reports that can help you optimize your workflow.

**Comment by hoyu310** [comment]
Thank you! I see all the resource metrics now in the log-stream path you mentioned, apologies that previously I didn't 'Expand row' and missed it.
